//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int RGV正常速度刻度 {
            get {
                return ((int)(this["RGV正常速度刻度"]));
            }
            set {
                this["RGV正常速度刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int RGV超速速度刻度 {
            get {
                return ((int)(this["RGV超速速度刻度"]));
            }
            set {
                this["RGV超速速度刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int RGV电量预警刻度 {
            get {
                return ((int)(this["RGV电量预警刻度"]));
            }
            set {
                this["RGV电量预警刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RGV低电报警刻度 {
            get {
                return ((int)(this["RGV低电报警刻度"]));
            }
            set {
                this["RGV低电报警刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int RGV警告电流刻度 {
            get {
                return ((int)(this["RGV警告电流刻度"]));
            }
            set {
                this["RGV警告电流刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int RGV危险电流刻度 {
            get {
                return ((int)(this["RGV危险电流刻度"]));
            }
            set {
                this["RGV危险电流刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int RGV最大电流刻度 {
            get {
                return ((int)(this["RGV最大电流刻度"]));
            }
            set {
                this["RGV最大电流刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RGV低温提醒刻度 {
            get {
                return ((int)(this["RGV低温提醒刻度"]));
            }
            set {
                this["RGV低温提醒刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int RGV高温提醒刻度 {
            get {
                return ((int)(this["RGV高温提醒刻度"]));
            }
            set {
                this["RGV高温提醒刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-100")]
        public int RGV最低温刻度 {
            get {
                return ((int)(this["RGV最低温刻度"]));
            }
            set {
                this["RGV最低温刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int RGV最高温刻度 {
            get {
                return ((int)(this["RGV最高温刻度"]));
            }
            set {
                this["RGV最高温刻度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RGV充电位位置 {
            get {
                return ((int)(this["RGV充电位位置"]));
            }
            set {
                this["RGV充电位位置"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int RGV轨道长度 {
            get {
                return ((int)(this["RGV轨道长度"]));
            }
            set {
                this["RGV轨道长度"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第一节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第一节车标记色"]));
            }
            set {
                this["第一节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第二节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第二节车标记色"]));
            }
            set {
                this["第二节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第三节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第三节车标记色"]));
            }
            set {
                this["第三节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第四节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第四节车标记色"]));
            }
            set {
                this["第四节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第五节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第五节车标记色"]));
            }
            set {
                this["第五节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第六节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第六节车标记色"]));
            }
            set {
                this["第六节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第七节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第七节车标记色"]));
            }
            set {
                this["第七节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第八节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第八节车标记色"]));
            }
            set {
                this["第八节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第九节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第九节车标记色"]));
            }
            set {
                this["第九节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第十节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第十节车标记色"]));
            }
            set {
                this["第十节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第11节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第11节车标记色"]));
            }
            set {
                this["第11节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第12节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第12节车标记色"]));
            }
            set {
                this["第12节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第13节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第13节车标记色"]));
            }
            set {
                this["第13节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第14节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第14节车标记色"]));
            }
            set {
                this["第14节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color 第15节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第15节车标记色"]));
            }
            set {
                this["第15节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color 第16节车标记色 {
            get {
                return ((global::System.Drawing.Color)(this["第16节车标记色"]));
            }
            set {
                this["第16节车标记色"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool 日志 {
            get {
                return ((bool)(this["日志"]));
            }
            set {
                this["日志"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8001/")]
        public string ServerPath {
            get {
                return ((string)(this["ServerPath"]));
            }
            set {
                this["ServerPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1:10010")]
        public string 控制服务地址 {
            get {
                return ((string)(this["控制服务地址"]));
            }
            set {
                this["控制服务地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1:10011")]
        public string 业务服务地址 {
            get {
                return ((string)(this["业务服务地址"]));
            }
            set {
                this["业务服务地址"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int AlgorithmOutTime {
            get {
                return ((int)(this["AlgorithmOutTime"]));
            }
            set {
                this["AlgorithmOutTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\PuzzleServer\\PicturePuzzleService\\HostWinform\\bin\\Debug\\concat_yolov560_m_640_" +
            "4_1031.engine")]
        public string EnginePath {
            get {
                return ((string)(this["EnginePath"]));
            }
            set {
                this["EnginePath"] = value;
            }
        }
    }
}
